### ISSUE TITLE
Is there a way to force Nextflow installation to cache?

### ISSUE THREAD

**Issue by maxulysse** [nf-core/setup-nextflow#9]
It never seems to cache whenever I relaunch failed jobs in sarek:
For example: https://github.com/nf-core/sarek/actions/runs/3839852344/jobs/6538177114

I can see that `Run actions/cache@v2` has:
```
Cache restored successfully
```
So something was cached there.

But for the `Install Nextflow`, it install everything from scratch:
```
Input version '22.10.1' resolved to Nextflow Version 22.10.1
Preparing to download from https://github.com/nextflow-io/nextflow/releases/download/v22.10.1/nextflow
Downloaded `nextflow` to /opt/hostedtoolcache/nextflow/22.10.1/x64 and added to PATH
(node:1863) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/hostedtoolcache/nextflow/22.10.1/x64/nextflow help
Downloading nextflow dependencies. It may require a few seconds, please wait .. 
```

**Comment by MillironX** [comment]
`actions/cache` that the workflow uses is different from `@actions/toolcache` that the action uses. ~~It looks to me like the `actions/cache` step is caching pip packages, not Nextflow files.~~ **Edit:** Now I see the added Nextflow cache. It looks like Nextflow was cached _before_ it was installed, though? Maybe that's part of the issue. It's still disturbing that `tool-cache` isn't pulling a cached version.

Would you mind rerunning with debug logging on? Most of the caching steps only give output for debug-level logging.

**Comment by maxulysse** [comment]
Removed that part, was trying some stuff out following examples in viralintegration, but not working there either.
But striped it out again, and this is the regular action to install Nextflow (First one did not exist, due to failures with API limit in previous GHA)
https://github.com/nf-core/sarek/actions/runs/3840015193/jobs/6540875099
3rd try, still installing Nextflow the same way:
https://github.com/nf-core/sarek/actions/runs/3840015193/jobs/6549912923
```
Input version 'latest-everything' resolved to Nextflow Version 22.12.0-edge
Preparing to download from https://github.com/nextflow-io/nextflow/releases/download/v22.12.0-edge/nextflow
Downloaded `nextflow` to /opt/hostedtoolcache/nextflow/22.12.0-edge/x64 and added to PATH
(node:1838) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
/opt/hostedtoolcache/nextflow/22.12.0-edge/x64/nextflow help
Downloading nextflow dependencies. It may require a few seconds, please wait .. 
Usage: nextflow [options] COMMAND [arg...]
```

**Comment by MillironX** [comment]
I've run some tests, and the language in the action is misleading. It will say "Preparing to download..." **even if** it is actually pulling from the tool cache. I can update that language in a future update.

Is there a particular reason you want to cache the Nextflow install beyond tool cache?

**Comment by maxulysse** [comment]
I see.
I was actually trying to see if I could do anything about the API limit

**Comment by MillironX** [comment]
That won't do anything, b/c the API is queried _every_ time to validate versions before the cache is checked. In retrospect, that was a poor design decision, and I've sketched out how that might be remedied in #5. It's going to take a considerable amount of effort to do that refactor, though.

**Comment by maxulysse** [comment]
ok, thanks a lot for all your comments
